import Link from "next/link";
import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Options from "@/components/header/Options";
import Footer from "@/components/footer/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NotFound() {
  return (
    <html>
      <body>
        <Header />
        <Options showTitle={false} />

        <div className="flex flex-col justify-center items-center gap-4 mx-auto mt-8 py-10 md:py-40">
          <h3>404 - Page Not Found</h3>
          <p className="text-center">
            We couldn&apos;t find the page you&apos;re looking for. Try searching for
            something else or return to the{" "}
            <Link href="/" className="underline">
              homepage
            </Link>
          </p>
        </div>

        <Footer />
      </body>
    </html>
  );
}
